#!/usr/bin/env python
#-*- coding: utf-8 -*-
import os
import sys
import time
import sqlite3

print("\t\t\t\t--------")
print("\t\t\t\tEXPOTRON")
print("\t\t\t\t--------\n")

def menu():
    os.system("cls")
    os.system("color e")
    def nosotros():
        os.system("cls")
        print("-----------------------")
        print("Que es el Expotron ?")
        print("-----------------------\n")
        print("El EXPOTRON es uno de los eventos de robotica mas grandes a nivel nacional, que se encarga de fomentar la investigacion y el desarrollo tecnologico en nuestro pais. Este evento año tras año reune a decenas de estudiantes de distintas parte del Peru y, para que en 3 dias demuestren sus habilidades y destrezas en temas de robotica y automatizacion en los concursos.\n")
        n=int(input("Presione '0' : "))
        if(n==0):
            print("-----------------------")
            print("Quienes somos?")
            print("-----------------------\n")
            print("Este evento esta organizado por la Rama Estudiantil IEEE-UNSA, y la Escuela Profesional de Ingenieria Electronica (EPIE) de la Universidad Nacional de San Agustin.\n")
            n=int(input("Presione '0' :"))
            if(n==0):
                print("-----------------------")
                print("Donde se realizara ?")
                print("-----------------------\n")
                print("Loza Deportiva de la Escuela Profesional de Ingenieria Electronica. \n")
                int(input("Presione '0' para regresar al MENU :"))
                if(n==0):
                    menu()
    def inscripcion():
        os.system("cls")
        def feria():
            os.system("cls")
            print("Llene los siguientes datos ...Para reservar su stand...")
            print("==================================")
            nempresa=input("Nombre de la empresa : ")
            nombref=input("Nombre :")
            apellidosf=input("Apellidos :")
            dnif=input("DNI : ")
            telefonof=input("Telefono :")
            correof=input("Correo electronico : ")
            descripcionf=input("Descripcion breve de que dara a conocer : ")

            con=sqlite3.connect("expotrom.s3db")
            cursor=con.cursor()
            cursor.execute("insert into Feria (nempresa,nombref,apellidosf,dnif,telefonof,correof,descripcionf) values ('"+nempresa+"','"+nombref+"','"+apellidosf+"','"+dnif+"','"+telefonof+"','"+correof+"','"+descripcionf+"')")
            con.commit()
            con.close()
            os.system("cls")
            print("UD. se registro con exito...\n")
            n=int(input("Presione '0' : "))
            if(n==0):
                inscripcion()
        def taller():
            os.system("cls")
            print("Llene los siguientes datos ...Para reservar su stand...")
            print("==================================")
            ntaller=input("Nombre del taller : ")
            nombreta=input("Nombre : ")
            apellidosta=input("Apellidos :")
            dnita=input("DNI : ")
            telefonota=input("Telefono :")
            correota=input("Correo electronico : ")
            descripcionta=input("Descripcion breve del taller : ")

            con=sqlite3.connect("expotrom.s3db")
            cursor=con.cursor()
            cursor.execute("insert into Taller (ntaller,nombreta,apellidosta,dnita,telefonota,correota,descripcionta) values ('"+ntaller+"','"+nombreta+"','"+apellidosta+"','"+dnita+"','"+telefonota+"','"+correota+"','"+descripcionta+"')")
            con.commit()
            con.close()
            os.system("cls")
            input("UD. se registro con exito...")
            n=int(input("Presione '0' : "))
            if(n==0):
                inscripcion()
        def proyectos():
            os.system("cls")
            print("Llene los siguientes datos ...Para exponer su proyecto...")
            print("==================================")
            nproyecto=input("Nombre del proyecto : ")
            nombrep=input("Nombre : ")
            apellidosp=input("Apellidos :")
            dnip=input("DNI : ")
            telefonop=input("Telefono :")
            correop=input("Correo electronico : ")
            descripcionp=input("Descripcion breve del proyecto : ")
            con=sqlite3.connect("expotrom.s3db")
            cursor=con.cursor()
            cursor.execute("insert into Proyecto (nproyecto,nombrep,apellidosp,dnip,telefonop,correop,descripcionp) values ('"+nproyecto+"','"+nombrep+"','"+apellidosp+"','"+dnip+"','"+telefonop+"','"+correop+"','"+descripcionp+"')")
            con.commit()
            con.close()
            os.system("cls")
            input("UD. se registro con exito...")
            n=int(input("Presione '0' : "))
            if(n==0):
                inscripcion()
        def competencias():
            def segvel():
                os.system("cls")
                print("Llene los siguientes datos ...Para inscribir su seguidor/velocista...")
                print("==================================")
                print("/t/tDatos del Participante ")
                print("==================================")
                nombres=input("Nombre : ")
                apellidoss=input("Apellidos :")
                dnis=input("DNI : ")
                telefonos=input("Telefono :")
                correos=input("Correo electronico : ")
                print("==================================")
                print("/t/tDatos del Seguidor/Velocista  ")
                print("==================================")
                nomsegvel=input("Nombre del S/V :")
                colorsegvel=input("Color del S/V :")
                materialsegvel=input("Material del S/V :")
                pesosegvel=input("Peso del S/V :")
                con=sqlite3.connect("expotrom.s3db")
                cursor=con.cursor()
                cursor.execute("insert into segvel (nombres,apellidoss,dnis,telefonos,correos,nomsegvel,colorsegvel,materialsegvel,pesosegvel) values ('"+nombres+"','"+apellidoss+"','"+dnis+"','"+telefonos+"','"+correos+"','"+nomsegvel+"','"+colorsegvel+"','"+materialsegvel+"','"+pesosegvel+"')")
                con.commit()
                con.close()
                os.system("cls")
                input("UD. se registro con exito ...")
                n=int(input("Presione '0' : "))
                if(n==0):
                    competencias()
            def minisumos():
                def medio():
                    os.system("cls")
                    print("Llene los siguientes datos ...Para exponer su minisumo...")
                    print("==================================")
                    print("/t/tDatos del Participante ")
                    print("==================================")
                    nombreme=input("Nombre : ")
                    apellidosme=input("Apellidos :")
                    dnime=input("DNI : ")
                    telefonome=input("Telefono :")
                    correome=input("Correo electronico : ")
                    print("==================================")
                    print("/t/tDatos del Seguidor/Velocista  ")
                    print("==================================")
                    nomsumo=input("Nombre del minisumo:")
                    colorsumo=input("Color del minisumo :")
                    matsumo=input("Material del minisumo :")
                    pesosumo=input("Peso del minisumo :")
                    con=sqlite3.connect("expotrom.s3db")
                    cursor=con.cursor()
                    cursor.execute("insert into medio (nombreme,apellidosme,dnime,telefonome,correome,nomsumo,colorsumo,matsumo,pesosumo) values ('"+nombreme+"','"+apellidosme+"','"+dnime+"','"+telefonome+"','"+correome+"','"+nomsumo+"','"+colorsumo+"','"+matsumo+"','"+pesosumo+"')")
                    con.commit()
                    con.close()
                    os.system("cls")
                    input("UD. se registro con exito ...")
                    n=int(input("Presione '0' : "))
                    if(n==0):
                        minisumos()
                def tres():
                    os.system("cls")
                    print("Llene los siguientes datos ...Para inscribir su minisumo ...")
                    print("==================================")
                    print("/t/tDatos del Participante ")
                    print("==================================")
                    nomt=input("Nombre : ")
                    apellidost=input("Apellidos :")
                    dnit=input("DNI : ")
                    telefonot=input("Telefono :")
                    correot=input("Correo electronico : ")
                    print("==================================")
                    print("/t/tDatos del Seguidor/Velocista  ")
                    print("==================================")
                    nomsumot=input("Nombre del minisumo :")
                    colorsumot=input("Color del S/V :")
                    matsumot=input("Material del minisumo :")
                    pesosumot=input("Peso del minisumo :")
                    con=sqlite3.connect("expotrom.s3db")
                    cursor=con.cursor()
                    cursor.execute("insert into tres (nomt,apellidost,dnit,telefonot,correot,nomsumot,colorsumot,matsumot,pesosumot) values ('"+nomt+"','"+apellidost+"','"+dnit+"','"+telefonot+"','"+correot+"','"+nomsumot+"','"+colorsumot+"','"+matsumot+"','"+pesosumot+"')")
                    con.commit()
                    con.close()
                    os.system("cls")
                    input("UD. se registro con exito ...")
                    n=int(input("Presione '0' : "))
                    if(n==0):
                        minisumos()
                os.system("cls")
                print("\n//////////CATEGORIAS///////////\n")
                print("-------------------------------")
                print("\t (1) 500 gr. ")
                print("-------------------------------")
                print("\t (2) 3 kgr. ")
                print("-------------------------------")
                print("\t (3) Volver al menu de competencias ")
                print("-------------------------------")
                deci=int(input("Digite una opcion del MENU DE COMPETENCIAS "))
                if deci==1:
                    medio()
                elif deci==2:
                    tres()
                elif deci==3:
                    competencias()
                else:
                    input("Digite una opcion valida ...")
                    minisumos()
            def mirosoft():
                os.system("cls")
                print("Llene los siguientes datos ...Para inscribir su robot(misoft)...")
                print("==================================")
                print("/t/tDatos del Participante ")
                print("==================================")
                nombrem=input("Nombre : ")
                apellidosm=input("Apellidos :")
                dnim=input("DNI : ")
                telefonom=input("Telefono :")
                correom=input("Correo electronico : ")
                print("==================================")
                print("/t/tDatos del Mirosoft  ")
                print("==================================")
                nomsoft1=input("Nombre del mirosoft 1 :")
                nomsoft2=input("Nombre del mirosoft 2 :")
                colsoft=input("Color de los mirosofts  :")
                materialsoft=input("Material de los mirosofts :")
                pesosoft1=input("Peso del mirosoft 1 :")
                pesosoft2=input("Peso del mirosoft 2 :")
                con=sqlite3.connect("expotrom.s3db")
                cursor=con.cursor()
                cursor.execute("inser into mirosoft (nombrem,apellidosm,dnim,telefonom,correom,nomsoft1,nomsoft2,colsoft,materialsoft,pesosoft1,pesosoft2) values ('"+nombrem+"','"+apellidosm+"','"+dnim+"','"+telefonom+"','"+correom+"','"+nomsoft1+"','"+nomsoft2+"','"+colsoft+"','"+materialsoft+"','"+pesosoft1+"','"+pesosoft2+"')")
                con.commit()
                con.close()
                os.system("cls")
                input("UD. se registro con exito ...")
                n=int(input("Presione '0' : "))
                if(n==0):
                    competencias()
            os.system("cls")
            print("\n//////////COMPETENCIAS///////////\n")
            print("-------------------------------")
            print("\t (1) Seguidores y Velocistas ")
            print("-------------------------------")
            print("\t (2) Minisumos ")
            print("-------------------------------")
            print("\t (3) Mirosoft ")
            print("-------------------------------")
            print("\t (4) Volver al MENU DE INSCRIPCIONES ")
            print("-------------------------------")
            opci=int(input("Digite una opcion del MENU DE COMPETENCIAS "))
            if opci==1:
                segvel()
            elif opci==2:
                minisumos()
            elif opci==3:
                mirosoft()
            elif opci==4:
                inscripcion()
            else:
                input("Digite una opcion valida ...")
                competencias()
        def warbots():
            os.system("cls")
            print("Llene los siguientes datos ...Para inscribir su warbot...")
            print("==================================")
            print("/t/tDatos del Participante ")
            print("==================================")
            nombrew=input("Nombre : ")
            apellidosw=input("Apellidos :")
            dniw=input("DNI : ")
            telefonow=input("Telefono :")
            correow=input("Correo electronico : ")
            print("==================================")
            print("/t/tDatos del Warbot  ")
            print("==================================")
            nomw=input("Nombre del Warbot  :")
            matw=input("Material Warbot :")
            pesow=input("Peso del Warbot :")
            asistentes=input("Numero de Asistentes :")
            con=sqlite3.connect("expotrom.s3db")
            cursor=con.cursor()
            cursor.execute("insert into Warbots (nombrew,apellidosw,dniw,telefonosw,correow,nomw,matw,pesow,asistentes) values ('"+nombrew+"','"+apellidosw+"','"+dniw+"','"+telefonow+"','"+correow+"','"+nomw+"','"+matw+"','"+pesow+"','"+asistentes+"')")
            con.commit()
            con.close()
            os.system("cls")
            input("UD. se registro con exito ...")
            n=int(input("Presione '0' : "))
            if(n==0):
                competencias()

        print("\n//////////INSCRIPCIONES ///////////\n")
        print("-------------------------------")
        print("\t (1) Feria de Tecnologia ")
        print("-------------------------------")
        print("\t (2) Talleres ")
        print("-------------------------------")
        print("\t (3) Proyectos ")
        print("-------------------------------")
        print("\t (4) Competencias ")
        print("-------------------------------")
        print("\t (5) WARBOTS ")
        print("-------------------------------")
        print("\t (6) Volver al MENU PRINCIPAL ")
        print("-------------------------------")
        opci=int(input("Digite una opcion del MENU DE INSCRIPCIONES... : "))
        if opci==1:
            feria()
        elif opci==2:
            taller()
        elif opci==3:
            proyectos()
        elif opci==4:
            competencias()
        elif opci==5:
            warbots()
        elif opci==6:
            menu()
        else:
            input("Digite una opcion valida ...")
            inscripcion()
    def cronograma():
        os.system("cls")
        def primero():
            os.system("cls")
            print("--------------------------------------------------------------------------")
            print("(9:00-10:00)  |                      Inaguracion                         |")
            print("--------------------------------------------------------------------------")
            print("(10:00-11:00) | Feria de Tecnologia |                 |                  |")
            print("--------------------------------------------------------------------------")
            print("(11:00-12:00) | Feria de Tecnologia |  Larvic -UCSP   |  CARRERAS KIDS   |")
            print("--------------------------------------------------------------------------")
            print("(12:00-13:00) | Feria de Tecnologia |      YURA       | SEGUIDOR JUNIOR  |")
            print("--------------------------------------------------------------------------")
            print("(13:00-14:00) | Feria de Tecnologia |                 |   SCRATCH        |")
            print("--------------------------------------------------------------------------")
            print("(14:00-15:00) | Feria de Tecnologia |                 |   RECICLAJE      |")
            print("--------------------------------------------------------------------------")
            print("(15:00-16:00) |   Taller Arduino    |                 |    Proyectos     |")
            print("--------------------------------------------------------------------------")
            print("(16:00-17:00) |   Taller Arduino    |                 |    Proyectos     |")
            print("--------------------------------------------------------------------------")
            print("(17:00-18:00) |   Taller Arduino    |                 |    Proyectos     |")
            print("--------------------------------------------------------------------------")
            print("(18:00-19:00) |                     |                 |    Proyectos     |")
            print("--------------------------------------------------------------------------")
            print("")
            n=int(input("Precione '0' para regresar al CRONOGRAMA : "))
            os.system("cls")
            if(n==0):
                cronograma()
        def segundo():
            os.system("cls")
            print("---------------------------------------------------------------------------------")
            print("(9:00-10:00)  |                                                                 |")
            print("---------------------------------------------------------------------------------")
            print("(10:00-11:00) | Taller de PLC  | Feria de Tecnologia |              | LEGO      |")
            print("---------------------------------------------------------------------------------")
            print("(11:00-12:00) | Taller de PLC  | Feria de Tecnologia | Tec Hunter   | LEGO      |")
            print("---------------------------------------------------------------------------------")
            print("(12:00-13:00) | Taller de PLC  | Feria de Tecnologia | Larvic UCSP  | SOCCER    |")
            print("---------------------------------------------------------------------------------")
            print("(13:00-14:00) | Taller de PLC  | Feria de Tecnologia |              | LIBRE     |")
            print("---------------------------------------------------------------------------------")
            print("(14:00-15:00) |                | Feria de Tecnologia | Eagle Diseño |           |")
            print("---------------------------------------------------------------------------------")
            print("(15:00-16:00) | Taller Arduino |        Taller       |   diseño     | Proyectos |")
            print("---------------------------------------------------------------------------------")
            print("(16:00-17:00) | Taller Arduino |         de          |  de PCBs     | Proyectos |")
            print("---------------------------------------------------------------------------------")
            print("(17:00-18:00) | Taller Arduino |      creacion de    |              | Proyectos |")
            print("---------------------------------------------------------------------------------")
            print("(18:00-19:00) |                |      videojuegos    |              | Proyectos |")
            print("---------------------------------------------------------------------------------")
            print("")
            n=int(input("Precione '0' para regresar al CRONOGRAMA : "))
            os.system("cls")
            if(n==0):
                cronograma()
        def tercero():
            os.system("cls")
            print("--------------------------------------------------------------------")
            print("(9:00-10:00)  |                                                    |")
            print("--------------------------------------------------------------------")
            print("(10:00-11:00) | Feria de Tecnologia |                | SEGUIDORES  |")
            print("--------------------------------------------------------------------")
            print("(11:00-12:00) | Feria de Tecnologia | Fablab TECSUP  | SEGUIDORES  |")
            print("--------------------------------------------------------------------")
            print("(12:00-13:00) | Feria de Tecnologia |    MECANOS     | VELOCISTAS  |")
            print("--------------------------------------------------------------------")
            print("(13:00-14:00) | Feria de Tecnologia |                | VELOCISTAS  |")
            print("--------------------------------------------------------------------")
            print("(14:00-15:00) | Feria de Tecnologia |                |             |")
            print("--------------------------------------------------------------------")
            print("(15:00-16:00) |                     |  Proyectos     | MINI SUMOS  |")
            print("--------------------------------------------------------------------")
            print("(16:00-17:00) |                     |  Proyectos     | MINU SUMOS  |")
            print("------------------------------------------------------------------- ")
            print("(17:00-18:00) |                     |  Proyectos     |  WAR BOTS   |")
            print("--------------------------------------------------------------------")
            print("(18:00-19:00) |                     |                |  WAR BOTS   |")
            print("--------------------------------------------------------------------")
            print("(19:00-20:00) |                     |                |  WAR BOTS   |")
            print("--------------------------------------------------------------------")
            print()
            n=int(input("Precione '0' para regresar al CRONOGRAMA : "))
            os.system("cls")
            if(n==0):
                cronograma()
        def cuarto():
            os.system("cls")
            print("---------------------------------------------------------")
            print("(9:00-10:00)  |                                         |")
            print("---------------------------------------------------------")
            print("(10:00-11:00) | Feria de Tecnologia | FINAL SEGUIDORES  |")
            print("---------------------------------------------------------")
            print("(11:00-12:00) | Feria de Tecnologia | FINAL VELOCISTA   |")
            print("---------------------------------------------------------")
            print("(12:00-13:00) | Feria de Tecnologia |    SUMOBOTS       |")
            print("---------------------------------------------------------")
            print("(13:00-14:00) | Feria de Tecnologia |      MIROSOFT     |")
            print("---------------------------------------------------------")
            print("(14:00-15:00) | Feria de Tecnologia |      MIROSOFT     |")
            print("---------------------------------------------------------")
            print("(15:00-16:00) |                                         |")
            print("---------------------------------------------------------")
            print("(16:00-17:00) |               CLAUSURA                  |")
            print("---------------------------------------------------------")
            print("(17:00-18:00) |                     |       WAR BOTS    |")
            print("---------------------------------------------------------")
            print("(18:00-19:00) |                     |       WAR BOTS    |")
            print("---------------------------------------------------------")
            print("(19:00-20:00) |                     |       WAR BOTS    |")
            print("---------------------------------------------------------")
            print("")
            n=int(input("Precione '0' para regresar al CRONOGRAMA : "))
            os.system("cls")
            if(n==0):
                cronograma()
        print("\n/////////////CRONOGRAMA//////////////\n")
        print("-------------------------------")
        print("\t (1) Primer dia")
        print("-------------------------------")
        print("\t (2) Segundo dia ")
        print("-------------------------------")
        print("\t (3) Tercer dia ")
        print("-------------------------------")
        print("\t (4) Cuarto dia ")
        print("-------------------------------")
        print("\t (5) Regresar al menu  ")
        print("-------------------------------")

        op=int(input("Digite una opcion : "))
        if op==1:
            primero()
        elif op==2:
            segundo()
        elif op==3:
            tercero()
        elif op==4:
            cuarto()
        elif op==5:
            menu()
        else:
            input("Digite una opcion valida ...")
            cronograma()
    def contactenos():
        os.system("cls")
        print("FACEBOOK : \n")
        print(" ---------------------------------------------")
        print("| https://www.facebook.com/IEEEUNSA/?fref=ts# | ")
        print(" ---------------------------------------------")
        n=int(input("Presione '0' para regresar al MENU :"))
        os.system("cls")
        if(n==0):
            menu()
    def inscritos():
        os.system("cls")
        def verferia():
            os.system("cls")
            print("Empresas Registradas ")
            print("======================= \n")
            con=sqlite3.connect("expotrom.s3db")
            cursor=con.cursor()
            cursor.execute("select * from Feria")
            for v in cursor :
                print("Codigo : ", v[0])
                print("Nombre de la Empresa : ", v[1])
                print("Nombre  : ", v[2])
                print("Apellidos  : ", v[3])
                print("Dni  : ", v[4])
                print("Telefono  : ", v[5])
                print("Correo electronico  : ", v[6])
                print("Descripcion  : ", v[7])
                print("\n--------------------------------\n")
            n=int(input("Presione '0' para regresar al MENU :"))
            if(n==0):
                inscritos()
            con.close()
        def vertaller():
            os.system("cls")
            print("Talleres Registradas ")
            print("======================= \n")
            con=sqlite3.connect("expotrom.s3db")
            cursor=con.cursor()
            cursor.execute("select * from Taller")
            for v in cursor :
                print("Codigo : ", v[0])
                print("Nombre del Taller : ", v[1])
                print("Nombre  : ", v[2])
                print("Apellidos  : ", v[3])
                print("Dni  : ", v[4])
                print("Telefono  : ", v[5])
                print("Correo electronico  : ", v[6])
                print("Descripcion : ", v[7])
                print("\n--------------------------------\n")

            n=int(input("Presione '0' para regresar al MENU :"))
            if(n==0):
                inscritos()
            con.close()
        def verproyectos():
            os.system("cls")
            print("Proyectos Registradas ")
            print("======================= \n")
            con=sqlite3.connect("expotrom.s3db")
            cursor=con.cursor()
            cursor.execute("select * from Proyecto ")
            for v in cursor :
                print("Codigo : ", v[0])
                print("Nombre del Taller : ", v[1])
                print("Nombre  : ", v[2])
                print("Apellidos  : ", v[3])
                print("Dni  : ", v[4])
                print("Telefono  : ", v[5])
                print("Correo electronico  : ", v[6])
                print("Descripcion : ", v[7])
                print("\n--------------------------------\n")

            n=int(input("Presione '0' para regresar al MENU :"))
            if(n==0):
                inscritos()
            con.close()
        def vercompetencias():
            def versegvel():
                os.system("cls")
                print("Seguidores y Velocistas Registrados ")
                print("======================= \n")
                con=sqlite3.connect("expotrom.s3db")
                cursor=con.cursor()
                cursor.execute("select * from segvel ")
                for v in cursor :
                    print("==================================")
                    print("/t/tDatos del Participante ")
                    print("==================================")
                    print("Codigo : ", v[0])
                    print("Nombre : ", v[1])
                    print("Apellidos :", v[2])
                    print("DNI : ", v[3])
                    print("Telefono :", v[4])
                    print("Correo electronico : ", v[5])
                    print("==================================")
                    print("/t/tDatos del Seguidor/Velocista  ")
                    print("==================================")
                    print("Nombre del S/V :", v[6])
                    print("Color del S/V :", v[7])
                    print("Material del S/V :", v[8])
                    print("Peso del S/V :", v[9])

                n=int(input("Presione '0' para regresar al MENU :"))
                if(n==0):
                    vercompetencias()
                con.close()
            def verminisumos():
                def vermedio():
                    os.system("cls")
                    print("Minisumos (500 gr.) Registrados ")
                    print("======================= \n")
                    con=sqlite3.connect("expotrom.s3db")
                    cursor=con.cursor()
                    cursor.execute("select * from medio ")
                    for v in cursor :
                        print("==================================")
                        print("/t/tDatos del Participante ")
                        print("==================================")
                        print("Codigo : ", v[0])
                        print("Nombre : ", v[1])
                        print("Apellidos :", v[2])
                        print("DNI : ", v[3])
                        print("Telefono :", v[4])
                        print("Correo electronico : ", v[5])
                        print("==================================")
                        print("/t/tDatos del Seguidor/Velocista  ")
                        print("==================================")
                        print("Nombre del Minisumo :", v[6])
                        print("Color del Minisumo :", v[7])
                        print("Material del Minisumo :", v[8])
                        print("Peso del Minisumo :", v[9])

                    n=int(input("Presione '0' para regresar al MENU :"))
                    if(n==0):
                        verminisumos()
                    con.close()
                def vertres():
                    os.system("cls")
                    print("Minisumos (3 kg.) Registrados ")
                    print("======================= \n")
                    con=sqlite3.connect("expotrom.s3db")
                    cursor=con.cursor()
                    cursor.execute("select * from tres ")
                    for v in cursor :
                        print("==================================")
                        print("/t/tDatos del Participante ")
                        print("==================================")
                        print("Codigo : ", v[0])
                        print("Nombre : ", v[1])
                        print("Apellidos :", v[2])
                        print("DNI : ", v[3])
                        print("Telefono :", v[4])
                        print("Correo electronico : ", v[5])
                        print("==================================")
                        print("/t/tDatos del Seguidor/Velocista  ")
                        print("==================================")
                        print("Nombre del Minisumo :", v[6])
                        print("Color del Minisumo :", v[7])
                        print("Material del Minisumo :", v[8])
                        print("Peso del Minisumo :", v[9])

                    n=int(input("Presione '0' para regresar al MENU :"))
                    if(n==0):
                        verminisumos()
                    con.close()
                os.system("cls")
                print("\n//////////CATEGORIAS///////////\n")
                print("-------------------------------")
                print("\t (1) 500 gr. ")
                print("-------------------------------")
                print("\t (2) 3 kgr. ")
                print("-------------------------------")
                print("\t (3) Volver al menu de competencias ")
                print("-------------------------------")
                deci=int(input("Digite una opcion del MENU DE COMPETENCIAS "))
                if deci==1:
                    vermedio()
                elif deci==2:
                    vertres()
                elif deci==3:
                    vercompetencias()
                else:
                    print("Digite una opcion valida .../n")
                    verminisumos()
            def vermirosoft():
                os.system("cls")
                print("Mirosofts Registrados ")
                print("======================= \n")
                con=sqlite3.connect("expotrom.s3db")
                cursor=con.cursor()
                cursor.execute("select * from mirosoft ")
                for v in cursor :
                    print("==================================")
                    print("/t/tDatos del Participante ")
                    print("==================================")
                    print("Codigo : ", v[0])
                    print("Nombre : ", v[1])
                    print("Apellidos :", v[2])
                    print("DNI : ", v[3])
                    print("Telefono :", v[4])
                    print("Correo electronico : ", v[5])
                    print("==================================")
                    print("/t/tDatos de los Mirasofts  ")
                    print("==================================")
                    print("Nombre del Mirosoft 1 :", v[6])
                    print("Nombre del Mirosoft 2 :", v[7])
                    print("Color del Mirosoft :", v[8])
                    print("Material del Mirosoft :", v[9])
                    print("Peso del Mirosoft 1 :", v[10])
                    print("Peso del Mirosoft 2 :", v[11])

                n=int(input("Presione '0' para regresar al MENU :"))
                if(n==0):
                    vercompetencias()
                con.close()
            os.system("cls")
            print("Competencias Registradas ")
            print("======================= \n")
            print("\n//////////COMPETENCIAS///////////\n")
            print("-------------------------------")
            print("\t (1) Seguidores y Velocistas ")
            print("-------------------------------")
            print("\t (2) Minisumos ")
            print("-------------------------------")
            print("\t (3) Mirosoft ")
            print("-------------------------------")
            print("\t (4) Volver al MENU DE INSCRIPCIONES ")
            print("-------------------------------")
            opci=int(input("Digite una opcion del MENU DE COMPETENCIAS "))
            if opci==1:
                versegvel()
            elif opci==2:
                verminisumos()
            elif opci==3:
                vermirosoft()
            elif opci==4:
                inscripcion()
            else:
                input("Digite una opcion valida ...")
                vercompetencias()
        def verwarbots():
            os.system("cls")
            print("Seguidores y Velocistas Registrados ")
            print("======================= \n")
            con=sqlite3.connect("expotrom.s3db")
            cursor=con.cursor()
            cursor.execute("select * from segvel ")
            for v in cursor :
                print("==================================")
                print("/t/tDatos del Participante ")
                print("==================================")
                print("Codigo : ", v[0])
                print("Nombre : ", v[1])
                print("Apellidos :", v[2])
                print("DNI : ", v[3])
                print("Telefono :", v[4])
                print("Correo electronico : ", v[5])
                print("==================================")
                print("/t/tDatos del Warbot  ")
                print("==================================")
                print("Nombre del Warbot :", v[6])
                print("Color del Warbot :", v[7])
                print("Material del Warbot :", v[8])
                print("Peso del Warbot :", v[9])
                print("Asistentes :", v[10])

                n=int(input("Presione '0' para regresar al MENU :"))
                if(n==0):
                    inscritos()
                con.close()

        print("\n//////////INSCRITOS ///////////\n")
        print("-------------------------------")
        print("\t (1) Feria de Tecnologia ")
        print("-------------------------------")
        print("\t (2) Talleres ")
        print("-------------------------------")
        print("\t (3) Proyectos ")
        print("-------------------------------")
        print("\t (4) Competencias ")
        print("-------------------------------")
        print("\t (5) WARBOTS ")
        print("-------------------------------")
        print("\t (6) Volver al MENU PRINCIPAL ")
        print("-------------------------------")
        opci=int(input("Digite una opcion del MENU DE INSCRIPCIONES... : "))
        if opci==1:
            verferia()
        elif opci==2:
            vertaller()
        elif opci==3:
            verproyectos()
        elif opci==4:
            vercompetencias()
        elif opci==5:
            verwarbots()
        elif opci==6:
            input("Presione 'Enter' para regresar al MENU PRINCIPAL ")
            menu()
        else:
            input("Digite una opcion valida ...")
            inscripcion()
    print("\n//////////MENU PRINCIPAL///////////\n")
    print("-------------------------------")
    print("\t (1) Sobre EXPOTRON")
    print("-------------------------------")
    print("\t (2) Inscripciones ")
    print("-------------------------------")
    print("\t (3) Ver cronograma ")
    print("-------------------------------")
    print("\t (4) Contactenos ")
    print("-------------------------------")
    print("\t (5) Inscritos ")
    print("-------------------------------")
    print("\t (6) Salir ")
    print("-------------------------------")

    opcion=int(input("Digite una opcion del Menu :"))

    if opcion==1:
        nosotros()
    elif opcion==2:
        inscripcion()
    elif opcion==3:
        cronograma()
    elif opcion==4:
        contactenos()
    elif opcion==5:
        inscritos()
    elif opcion==6:
        print("El programa se cerrara ...")
        time.sleep(3)
        sys.exit()
    else:
        print("Digite una opcion valida  ")
        time.sleep(2)
        os.system("cls")
        menu()
menu()





